// Braum 单 Worker 入口：Hono API + Next.js + Cloudflare Cron

// OpenNext 会在生产构建时生成此模块。
// @ts-expect-error generated by opennextjs-cloudflare build
import nextWorker from './apps/web/.open-next/worker.js'
import apiWorker from './apps/api/src/index'
import type { Env } from './apps/api/src/env'

export { RealtimeHub } from './apps/api/src/realtime/hub'

function isApiRequest(pathname: string): boolean {
  return pathname === '/health' || pathname.startsWith('/api/')
}

export default {
  fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const pathname = new URL(request.url).pathname
    return isApiRequest(pathname)
      ? apiWorker.fetch(request, env, ctx)
      : nextWorker.fetch(request, env, ctx)
  },

  scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext): Promise<void> {
    return apiWorker.scheduled(event, env, ctx)
  },
}
